from setuptools import setup, find_packages

setup(
    name="Siance Backend",
    version="0.1.0",
    packages=find_packages(),
    scripts=["bin/siance-backend"],
    # url="http://pypi.python.org/pypi/PackageName/",
    url="http://siance.asn.i2",
    license="LICENSE.txt",
    description="The backend of the SIANCE project.",
    long_description=open("README.txt").read(),
    install_requires=[
        # "siancedb",
        "prefect",
        "unidecode",
        "click",
        "wget",
        "pydantic",
        "sqlalchemy",
        "psycopg2",
        "openpyxl",
        "xlrd",
        "elasticsearch",
        "pytest",
        "fastapi",
        "python-jose",
        "appdirs",
        "astroid",
        "backcall",
        "cython",
        "blis",
        "dateparser",
        "DateTime",
        "feedparser",
        "matplotlib",
        "numpy",
        "schedule",
        "typed-ast",
        "tika",
        "spacy",
        "spacy-lookups-data",
        "sklearn",
        "sentencepiece",
        "sentence-transformers",
        "sklearn-hierarchical-classification",
        "scikit-learn",
        "scipy",
        "rope",
        "requests",
        "regex",
        "plotly",
        "pandas",
        "sacremoses",
        "plac",
        "aiofiles",
        "uvicorn",
        "unidecode",
    ],
)
