import spacy
from spacy.lang.fr import French


def prepare_sentencizer() -> spacy.language.Language:
    """
    Wrapper returning the spacy sentencizer for French language
    """
    nlp = French()
    nlp.add_pipe("sentencizer")
    return nlp


def prepare_sentencizer_training() -> spacy.language.Language:
    """
    This variant of sentencizer also cuts long sentences in shorter strings (e.g: ";" is considered as a separator)
    As a consequence, when only a few words are labelled by an inspector, the label can be expanded merely to the relevant part of the sentence
    """
    punct_chars = [
        "!",
        ".",
        "?",
        "։",
        "؟",
        "۔",
        "܀",
        "܁",
        "܂",
        "߹",
        "।",
        "॥",
        "၊",
        "။",
        "።",
        "፧",
        "፨",
        "᙮",
        "᜵",
        "᜶",
        "᠃",
        "᠉",
        "᥄",
        "᥅",
        "᪨",
        "᪩",
        "᪪",
        "᪫",
        "᭚",
        "᭛",
        "᭞",
        "᭟",
        "᰻",
        "᰼",
        "᱾",
        "᱿",
        "‼",
        "‽",
        "⁇",
        "⁈",
        "⁉",
        "⸮",
        "⸼",
        "꓿",
        "꘎",
        "꘏",
        "꛳",
        "꛷",
        "꡶",
        "꡷",
        "꣎",
        "꣏",
        "꤯",
        "꧈",
        "꧉",
        "꩝",
        "꩞",
        "꩟",
        "꫰",
        "꫱",
        "꯫",
        "﹒",
        "﹖",
        "﹗",
        "！",
        "．",
        "？",
        "𐩖",
        "𐩗",
        "𑁇",
        "𑁈",
        "𑂾",
        "𑂿",
        "𑃀",
        "𑃁",
        "𑅁",
        "𑅂",
        "𑅃",
        "𑇅",
        "𑇆",
        "𑇍",
        "𑇞",
        "𑇟",
        "𑈸",
        "𑈹",
        "𑈻",
        "𑈼",
        "𑊩",
        "𑑋",
        "𑑌",
        "𑗂",
        "𑗃",
        "𑗉",
        "𑗊",
        "𑗋",
        "𑗌",
        "𑗍",
        "𑗎",
        "𑗏",
        "𑗐",
        "𑗑",
        "𑗒",
        "𑗓",
        "𑗔",
        "𑗕",
        "𑗖",
        "𑗗",
        "𑙁",
        "𑙂",
        "𑜼",
        "𑜽",
        "𑜾",
        "𑩂",
        "𑩃",
        "𑪛",
        "𑪜",
        "𑱁",
        "𑱂",
        "𖩮",
        "𖩯",
        "𖫵",
        "𖬷",
        "𖬸",
        "𖭄",
        "𛲟",
        "𝪈",
        "｡",
        "。",
        "\n\n",
        ";",
    ]
    config = {"punct_chars": punct_chars}
    nlp = French()
    nlp.add_pipe("sentencizer", config=config)
    return nlp
